#!/bin/sh

# PROVIDE: WXCOIN
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# WXCOIN_enable (bool): Set to NO by default. Set this variable to YES if you want to enable WXCOIN service.
# WXCOIN_config (path): Set to /usr/local/etc/WXCOIN.conf by default.
# WXCOIN_user:  The user account WXCOIN daemon runs as. It uses 'root' user by default.
# WXCOIN_group: The group account WXCOIN daemon runs as. It uses 'wheel' group by default.
# WXCOIN_datadir (str): Default to "/var/db/WXCOIN". Base data directory.

. /etc/rc.subr

name=WXCOIN
rcvar=WXCOIN_enable

: ${WXCOIN_enable:=NO}
: ${WXCOIN_config=/usr/local/etc/WXCOIN.conf}
: ${WXCOIN_datadir=/var/db/WXCOIN}
: ${WXCOIN_user="root"}
: ${WXCOIN_group="wheel"}

required_files=${WXCOIN_config}
command=/usr/local/bin/WXCOINd
WXCOIN_chdir=${WXCOIN_datadir}
pidfile="${WXCOIN_datadir}/WXCOINd.pid"
stop_cmd=WXCOIN_stop
command_args="-conf=${WXCOIN_config} -datadir=${WXCOIN_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

WXCOIN_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${WXCOIN_datadir}
	[ $? -eq 0 ] && chown -R ${WXCOIN_user}:${WXCOIN_group} ${WXCOIN_datadir}
}

WXCOIN_prestart()
{
	if [ ! -d "${WXCOIN_datadir}/." ]; then
		WXCOIN_create_datadir || return 1
	fi
}

WXCOIN_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

WXCOIN_stop()
{
    WXCOIN_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${WXCOIN_config} -datadir=${WXCOIN_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
